Job model
AlexKochurov/job_prospector pull request #11
Opened 2018-11-19 17:10 UTC by AlexKochurov

2018-11-19 17:17 UTC, Mehonoshin requested changes

2018-11-19 17:17 UTC, Mehonoshin commented on app/models/job_entry.rb
> +class JobEntry < ApplicationRecord
Почему не просто `Job?`

2018-11-19 17:17 UTC, Mehonoshin commented on db/migrate/20181119164920_add_slaries_to_job_entry.rb
> +    add_monetize :job_entries, :salary
почему бы не назвать `salary_from`, `salary_to`

2018-11-19 17:17 UTC, Mehonoshin commented on test/fixtures/job_entries.yml
> +# == Schema Information
удаляем папку `test`

2018-11-19 17:17 UTC, Mehonoshin commented on test/models/job_entry_test.rb
> +class JobEntryTest < ActiveSupport::TestCase
Это удаляем, и давай добавим тесты на Rspec для этой модели.
Заюзай shoulda_matchers

2018-11-19 17:17 UTC, Mehonoshin commented on config/initializers/money.rb
> +  # Set default bank object
Комменты из конфигов имеет смысл удалить

2018-11-19 17:26 UTC, adradek commented on db/migrate/20181119164920_add_slaries_to_job_entry.rb
> +    add_monetize :job_entries, :salary
Я думаю, это вопрос вкуса. Если в вакансии будет указана ЗП, то в большинстве случаев там будет одно значение. Мы, конечно, можем договориться, что это будет `salary_from`, но мне этот вариант не особо нравится.

2018-11-19 17:48 UTC, AlexKochurov commented on app/models/job_entry.rb
> +class JobEntry < ApplicationRecord
Переименовал

2018-11-19 19:50 UTC, Mehonoshin commented on db/migrate/20181119164920_add_slaries_to_job_entry.rb
> +    add_monetize :job_entries, :salary
Это вопрос консистентности. Логично что если есть верхний предел зарплаты, то возможен и нижний. А если цифра одинаковая то оба значения делаем равными.
Это же поможет нам при организации поиска по ЗП, не придется делать кастомную логику для случаев когда только одна зп.

2018-11-20 07:39 UTC, Mehonoshin commented on spec/spec_helper.rb
> +# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
Я бы почистил и этот файл :) Чтобы мы сразу видели все опции которые включены для наших тестов

2018-11-20 07:53 UTC, Mehonoshin approved these changes

2018-11-20 08:05 UTC, merged